# REF: https://qiita.com/gldn/items/2a8486c4d7a42d7a0f1f
# REF: https://qiita.com/juhn/items/274e44ee80354a39d872
# REF: https://qiita.com/Manatee/items/58d0f98a15656ed65136

version: "2"

# networks:
#   bridge:
#     driver: bridge

services:
  app:
    build: ./server/
    ports:
      - "8080:1323"
    links:
      - mysql

  mysql:
    build: ./config/mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: noritubusi_map
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "Asia/Tokyo"
    ports:
      - "3314:3306"
    volumes:
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
      # - ./log/mysql:/var/log/mysql

volumes:
  mongodb-data: {}
  mysql-data: {}
