# REF: https://qiita.com/gldn/items/2a8486c4d7a42d7a0f1f

version: '2'

# networks:
#   bridge:
#     driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment: 
      - 'MONGODB_USER=user'
      - 'MONGODB_PASS=pAssWord'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

volumes:
  mongodb-data: {}
