# REF: https://qiita.com/gldn/items/2a8486c4d7a42d7a0f1f
# REF: https://qiita.com/juhn/items/274e44ee80354a39d872
# REF: https://qiita.com/Manatee/items/58d0f98a15656ed65136

version: "2"

# networks:
#   bridge:
#     driver: bridge

services:
  app:
    container_name: go_server
    env_file: .env
    build: ./config/app
    command: ./delayed_start
    volumes:
      - ${PWD}/app:/go/src/noritubusi-map/backend/app
    ports:
      - "1323:1323"
    links:
      - mysql:stationdb
      - redis:redis
    depends_on:
      - mysql
      - redis
    tty: true

  mysql:
    container_name: db
    env_file: .env
    build: ./config/mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3314:3306"
    volumes:
      - ${PWD}/config/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/config/mysql/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
      # - ./log/mysql:/var/log/mysql

  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  mysql-data: {}
  redis-data: {}
