swagger: '2.0'
info:
  description: 乗りつぶしMAPのAPIです
  version: 0.0.1
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: mjtakenon@mjtakenon
host: localhost
basePath: /
tags:
  - name: railway
    description: 路線情報について
  - name: station
    description: 駅情報について
  - name: user
    description: ユーザの管理と乗車記録について
schemes:
  - http
paths:
  /railways:
    get:
      tags:
        - railway
      summary: 路線情報取得
      description: ''
      operationId: getRailwaysInfo
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: 路線情報取得が成功
        '400':
          description: 不正なパラメータ
  /stations:
    get:
      tags:
        - station
      summary: 駅情報取得
      description: ''
      operationId: getStationsInfo
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: 駅情報取得が成功
        '400':
          description: 不正なパラメータ
  '/users/{userid}':
    get:
      tags:
        - user
      summary: ユーザ情報取得
      description: ''
      operationId: getUserInfo
      produces:
        - application/json
      parameters:
        - name: userid
          in: path
          description: Created user object
          required: true
          type: string
      responses:
        '200':
          description: ユーザ情報の取得が成功
        '404':
          description: ユーザが見つからなかった
    put:
      tags: 
        - user
      summary: ユーザ情報の変更
      description: ''
      parameters:
        - name: userid
          in: path
          description: Created user object
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: 情報変更が失敗
    delete:
      tags: 
        - user
      summary: ユーザの削除
      description: ''
      parameters:
        - name: userid
          in: path
          description: Created user object
          required: true
          type: string
      responses:
        '200':
          description: OK
  /signin:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: string
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: Invalid username/password supplied
    post:
      tags: 
        - user
      summary: ログイン情報受け取り
      description: ''
      responses:
        '200':
          description: OK
    delete:
      tags:
        - user
      summary: ログアウト
      description: ''
      operationId: logoutUser
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
  /signup:
    get:
      tags: 
        - user
      summary: ユーザ登録ページ取得
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags: 
        - user
      summary: 入力されたユーザ情報受取
      description: ''
      responses:
        '200':
          description: OK
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
    
