FROM golang:1.12.0 AS builder
WORKDIR $GOPATH/src/noritubusi-map/server
COPY . .

RUN go get -u github.com/golang/dep/cmd/dep
RUN dep ensure
RUN CGO_ENABLED=0 GOOS=linux go build -o server

FROM alpine:latest
ENV GOPATH=$HOME/go
COPY --from=builder $GOPATH/src/noritubusi-map/server /
CMD ["/server"]